### ISSUE TITLE
Restrict sudo command for SSH Certificate ForcedCommand

### ISSUE THREAD

**Issue by stoggi** [uber/pam-ussh#13]
One of the options for an SSH certificate is `force-command` (https://man.openbsd.org/ssh-keygen.1#force-command).

Would it be possible to limit the command that a user is able to execute with sudo if the `force-command` is set in the SSH certificate?

This would be super useful to be able to issue a certificate for a user with sudo permissions for one particular command without knowing the command in advance (otherwise you could user the sudoers file).

Is this possible in the PAM? Do you have access to the command that is to be run? I'm happy to contribute this feature with a little guidance in the right direction :)

**Comment by pmoody-** [comment]
I think this is a sudo thing. pam doesn't know anything about the particulars of the authentication request coming in. It just knows, like, "application <X> has asked that the user claiming to be <Y> be authenticated, so I need to go read what authentication mechanisms application <X> has configured"

Also, if there's a force-command, then the sshd to which the user authenticates would make the user execute that command during authentication.

you could see about stuffing the allowed commands into the ssh certificate Extensions map (https://godoc.org/golang.org/x/crypto/ssh#Permissions), like
```
   allowed-sudo-commands: "shutdown -h now, rm -rf /",
```
but then it would be up to sudo to pull those out of the certificate.

sorry :-/

**Comment by stoggi** [comment]
Ah, that's a shame. Interesting link about custom extensions. I'll need to do some reading on how PAM works.

> Also, if there's a force-command, then the sshd to which the user authenticates would make the user execute that command during authentication.

I was thinking you could have multiple certificates in your ssh-agent, that you would forward to the host.

I suppose you could achieve something similar by giving a user a ssh certificate for `root`, the `force-command` that you want to be able to run, and `source-address` as `127.0.0.1`. Then you could run a single command as root by invoking SSH on the same host. I'm not saying this is a _good_ idea. 🤔 

Thanks for your response, I'll close the issue.

**Comment by pmoody-** [comment]
> I suppose you could achieve something similar by giving a user a ssh certificate for root, the force-command that you want to be able to run, and source-address as 127.0.0.1. Then you could run a single command as root by invoking SSH on the same host. I'm not saying this is a good idea. 🤔

yeah, you could do that (we did something sort of similar back at uber for granting 'breakglass' access to hosts). but if you go that far, you're sort of using sshd like sudo, and i'm not sure it wouldn't just be easier to setup your sudoers file to allow the command in question.

anyway, thanks for taking the time to think through this and come up with suggestions.
