### ISSUE TITLE
Reporting potential security issues

### ISSUE THREAD

**Issue by pquerna** [uber/pam-ussh#2]
If there is a potential security issue with this project, should it be reported via the [uber hackerone program](https://hackerone.com/uber) or another method?

Thanks!

**Comment by pmoody-** [comment]
good question, one sec.

**Comment by pmoody-** [comment]
Ok Paul.

thanks for checking on this. Potential security issues should be submitted to the hackerone bugbounty program and the folks watching the bugbounty submissions will determine bounty eligibility.

Thanks again!
