### ISSUE TITLE
Project still alive? 

### ISSUE THREAD

**Issue by FlxPeters** [uber/pam-ussh#25]
Hey there and first a big thanks for providing this project. We try around with certificate based authentication at the moment and this seams to be the perfect fit to enable sudo via certs without having passwordless sudo.
Before using it in production I have some concerns on the health of the project as there is no release and some open PRs. 

So just a simple question: Is this project still alive and maintained? 

Thanks :-)

**Comment by pmoody-** [comment]
Hey Felix,

I left uber a while ago and I haven't been at a job that's used this module since then, but for some definition of maintained, this project is still maintained.

thanks for the poke, though. I'll take a look at your github actions pr.

**Comment by FlxPeters** [comment]
Thanks for the feedback. I close the issue then.
